document.write(
	"<div class=\"footer\">"
	+"	<ul class=\"ul2\">"
	+"		<li><a href=\"parters\">合作机构</a></li>"
	+"		<li><a>|</a></li>"
	+"		<li><a href=\"aboutus.html\">关于杏缘</a></li>"
	+"		<li><a>|</a></li>"
	+"		<li><a href=\"team.html\">团队介绍</a></li>"
	+"		<li><a>|</a></li>"
	+"		<li><a href=\"joinus.html\">加入我们</a></li>"
	+"		<li><a>|</a></li>"
	+"		<li><a href=\"contactus.html\">联系我们</a></li>"
	+"	</ul>"
	+"	<div><span>广州市高新技术产业开发区科学大道112号科学城绿地中央广场A1栋2305房</span></div>"
	+"	<div><span>粤ICP备16065370号</span></div>"
	+"	<div><span>2017 广州市杏缘信息科技有限公司版权所有</span></div>"
	+"</div>"
);